# Generated by Django 3.0.5 on 2020-05-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='creator',
            field=models.CharField(default='', editable=False, max_length=500),
        ),
    ]
